---
# Adds Google Assistant
#
# https://www.home-assistant.io/components/google_assistant
#
google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  expose_by_default: false
  entity_config: !include_dir_merge_named ../../assistants/google
