---
# The HomeKit component allows you to forward entities from Home Assistant
# to Apple HomeKit, so they can be controlled from Apple’s Home app and Siri.
#
# https://www.home-assistant.io/components/homekit
#
homekit:
  # Stop the HomeKit Server from starting automatically after the Home Assistant
  # Core Setup is done (zwave needs to start first).
  auto_start: false

  name: Spiegell

  # Filters for entities to be included / excluded from HomeKit.
  filter: !include_dir_merge_named ../../assistants/siri/filters

  # Configuration for specific entities. Allows customization of names and types
  entity_config: !include_dir_merge_named ../../assistant/siri/entities