---
# Sets up Home Assistant.
#
# Basically, everything that doesn't have to be in the main configuration.yaml.
#
homeassistant:

  # Individual entities
  customize: !include_dir_merge_named ../customizations/entities

  # Pattern based
  customize_glob: !include_dir_merge_named ../customizations/globs
