- id: '1646642370951'
  alias: Zolder uit na zonsopgang
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:30:00
  condition: []
  action:
  - type: turn_off
    device_id: 85a76f41b8be7d8a35ba5c1294f894dd
    entity_id: light.zolder
    domain: light
  mode: single
