---
#
# This is my Home Assistant configuration.
#
# The setup is following Frenck's idea for configuring Home Assistant, using single files for single purposes.
# This configuration.yaml file is used to bootstrap the rest.
#
# Frenck's repo: https://github.com/frenck/home-assistant-config (concept as it was at e75614b)
#
homeassistant:

  # Name of this Home Assistant
  name: spiegell

  # MFA setup, using TOTP
  auth_mfa_modules:
    - type: totp

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  # Packages
  packages: !include_dir_named integrations
