---
# Example configuration.yaml entry
alias: Update Available Notification
trigger:
  - platform: state
    entity_id: binary_sensor.updater
    # from: 'off'
    to: 'on'
action:
  - service: notify.slack
    data_template:
      message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
