---
# Starts Homekit after zwave has started
alias: Start HomeKit
hide_entity: true
trigger:
- platform: event
  event_type: zwave.network_ready
- platform: event
  event_type: zwave.network_complete
action:
- service: homekit.start
