---
alias: Kerstster wit
trigger:
- device_id: 6777b6bcd77f46228258711b57563f5f
  domain: light
  entity_id: light.keuken_level
  platform: device
  type: turned_on
condition:
- condition: device
  device_id: b58150812dd44761972856ae428e93f9
  domain: light
  entity_id: light.olielamp
  type: is_on
action:
- service: light.turn_on
  entity_id: light.olielamp
  data:
    rgb_color: [255, 220, 182]
    effect: none
